server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  profile.active: dev, test, prod
  datasource:
    platform: mysql
    url: ${DB_URL:jdbc:mysql://localhost:3306/stock}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"